name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push to Heroku
      run: git push heroku master
    - name: Heroku open
      run: heroku open
        
